"""Type stubs for psutil library."""

from collections.abc import Iterator
from typing import Any, NamedTuple

__all__ = [
    "AccessDenied",
    "NoSuchProcess",
    "Process",
    "TimeoutExpired",
    "ZombieProcess",
    "boot_time",
    "cpu_count",
    "cpu_freq",
    "cpu_percent",
    "cpu_stats",
    "cpu_times",
    "cpu_times_percent",
    "disk_io_counters",
    "disk_partitions",
    "disk_usage",
    "getloadavg",
    "net_connections",
    "net_if_addrs",
    "net_if_stats",
    "net_io_counters",
    "pid_exists",
    "pids",
    "process_iter",
    "sensors_battery",
    "sensors_fans",
    "sensors_temperatures",
    "swap_memory",
    "users",
    "virtual_memory",
    "wait_procs",
]

class NoSuchProcess(Exception):
    """Process no longer exists."""

    pid: int
    name: str | None
    msg: str

class ZombieProcess(NoSuchProcess):
    """Process is a zombie."""

class AccessDenied(Exception):
    """Access denied."""

    pid: int | None
    name: str | None
    msg: str

class TimeoutExpired(Exception):
    """Timeout expired."""

    seconds: float
    pid: int | None
    name: str | None

# CPU
def cpu_percent(
    interval: float | None = None, percpu: bool = False
) -> float | list[float]: ...
def cpu_count(logical: bool = True) -> int | None: ...
def cpu_stats() -> Any: ...
def cpu_times(percpu: bool = False) -> Any: ...
def cpu_times_percent(interval: float = 0.1, percpu: bool = False) -> Any: ...
def cpu_freq(percpu: bool = False) -> Any: ...
def getloadavg() -> tuple[float, float, float]: ...

# Memory
class svmem(NamedTuple):
    total: int
    available: int
    percent: float
    used: int
    free: int
    active: int | None
    inactive: int | None
    buffers: int | None
    cached: int | None
    shared: int | None

class sswap(NamedTuple):
    total: int
    used: int
    free: int
    percent: float
    sin: int
    sout: int

def virtual_memory() -> svmem: ...
def swap_memory() -> sswap: ...

# Disk
class sdiskusage(NamedTuple):
    total: int
    used: int
    free: int
    percent: float

class sdiskpart(NamedTuple):
    device: str
    mountpoint: str
    fstype: str
    opts: str
    maxfile: int | None
    maxpath: int | None

def disk_usage(path: str) -> sdiskusage: ...
def disk_partitions(all: bool = False) -> list[sdiskpart]: ...
def disk_io_counters(
    perdisk: bool = False, nowrap: bool = True
) -> Any | dict[str, Any] | None: ...

# Network
def net_io_counters(
    pernic: bool = False, nowrap: bool = True
) -> Any | dict[str, Any] | None: ...
def net_connections(kind: str = "inet") -> list[Any]: ...
def net_if_addrs() -> dict[str, list[Any]]: ...
def net_if_stats() -> dict[str, Any]: ...

# Sensors
def sensors_temperatures(fahrenheit: bool = False) -> dict[str, list[Any]]: ...
def sensors_fans() -> dict[str, list[Any]]: ...
def sensors_battery() -> Any | None: ...

# Other system info
def boot_time() -> float: ...
def users() -> list[Any]: ...

# Process management
def pids() -> list[int]: ...
def pid_exists(pid: int) -> bool: ...
def process_iter(
    attrs: list[str] | None = None, ad_value: Any = None
) -> Iterator[Process]: ...
def wait_procs(
    procs: list[Process], timeout: float | None = None, callback: Any | None = None
) -> tuple[list[Process], list[Process]]: ...

class Process:
    """Process class."""

    def __init__(self, pid: int | None = None) -> None: ...
    @property
    def pid(self) -> int: ...
    def ppid(self) -> int: ...
    def parent(self) -> Process | None: ...
    def parents(self) -> list[Process]: ...
    def children(self, recursive: bool = False) -> list[Process]: ...
    def name(self) -> str: ...
    def exe(self) -> str: ...
    def cmdline(self) -> list[str]: ...
    def environ(self) -> dict[str, str]: ...
    def create_time(self) -> float: ...
    def as_dict(
        self, attrs: list[str] | None = None, ad_value: Any = None
    ) -> dict[str, Any]: ...
    def status(self) -> str: ...
    def cwd(self) -> str: ...
    def username(self) -> str: ...
    def uids(self) -> Any: ...
    def gids(self) -> Any: ...
    def terminal(self) -> str | None: ...
    def nice(self, value: int | None = None) -> int: ...
    def ionice(self, ioclass: int | None = None, value: int | None = None) -> Any: ...
    def rlimit(
        self, resource: int, limits: tuple[int, int] | None = None
    ) -> tuple[int, int]: ...
    def io_counters(self) -> Any: ...
    def num_ctx_switches(self) -> Any: ...
    def num_fds(self) -> int: ...
    def num_handles(self) -> int: ...
    def num_threads(self) -> int: ...
    def threads(self) -> list[Any]: ...
    def cpu_times(self) -> Any: ...
    def cpu_percent(self, interval: float | None = None) -> float: ...
    def cpu_affinity(self, cpus: list[int] | None = None) -> list[int] | None: ...
    def cpu_num(self) -> int: ...
    def memory_info(self) -> Any: ...
    def memory_info_ex(self) -> Any: ...
    def memory_full_info(self) -> Any: ...
    def memory_percent(self, memtype: str = "rss") -> float: ...
    def memory_maps(self, grouped: bool = True) -> list[Any]: ...
    def open_files(self) -> list[Any]: ...
    def connections(self, kind: str = "inet") -> list[Any]: ...
    def is_running(self) -> bool: ...
    def send_signal(self, sig: int) -> None: ...
    def suspend(self) -> None: ...
    def resume(self) -> None: ...
    def terminate(self) -> None: ...
    def kill(self) -> None: ...
    def wait(self, timeout: float | None = None) -> int | None: ...
    def poll(self) -> int | None: ...
