version: '3.8'

services:
  ai-trading-bot:
    build:
      context: .
      dockerfile: Dockerfile.vps
      args:
        EXCHANGE_TYPE: ${EXCHANGE_TYPE:-coinbase}
    container_name: ai-trading-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - EXCHANGE__EXCHANGE_TYPE=${EXCHANGE_TYPE:-coinbase}
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - trading-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  trading-net:
    driver: bridge