version: '3.8'

services:
  ai-trading-bot:
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /var/tmp:noexec,nosuid,size=50m
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    user: "1000:1000"
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
