version: '3.8'

# Docker Secrets Configuration for Sensitive Data
# This file extends the main docker-compose.yml with secure secret management

secrets:
  # OpenAI API Key
  openai_api_key:
    external: true
    external_name: ai_trading_bot_openai_key

  # Coinbase API Credentials
  coinbase_api_key:
    external: true
    external_name: ai_trading_bot_coinbase_api_key

  coinbase_private_key:
    external: true
    external_name: ai_trading_bot_coinbase_private_key

  # Bluefin Private Key
  bluefin_private_key:
    external: true
    external_name: ai_trading_bot_bluefin_key

  # Additional secrets for future use
  database_password:
    external: true
    external_name: ai_trading_bot_db_password

  jwt_secret:
    external: true
    external_name: ai_trading_bot_jwt_secret

services:
  ai-trading-bot:
    secrets:
      - openai_api_key
      - coinbase_api_key
      - coinbase_private_key
      - bluefin_private_key
    environment:
      # Override environment variables to use secrets
      - SECRETS_ENABLED=true
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key
      - COINBASE_API_KEY_FILE=/run/secrets/coinbase_api_key
      - COINBASE_PRIVATE_KEY_FILE=/run/secrets/coinbase_private_key
      - BLUEFIN_PRIVATE_KEY_FILE=/run/secrets/bluefin_private_key

  mcp-memory:
    secrets:
      - database_password
      - jwt_secret
    environment:
      - SECRETS_ENABLED=true
      - DATABASE_PASSWORD_FILE=/run/secrets/database_password
      - JWT_SECRET_FILE=/run/secrets/jwt_secret

  # Security sidecar for secret rotation
  secret-rotator:
    image: alpine:3.19
    secrets:
      - openai_api_key
      - coinbase_api_key
      - coinbase_private_key
      - bluefin_private_key
    volumes:
      - ./scripts/security:/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: /scripts/rotate-secrets.sh
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
    networks:
      - ai-trading-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=10m
