version: '3.8'

services:
  trading-bot-slim:
    build:
      context: .
      dockerfile: Dockerfile.slim
      args:
        BUILD_DATE: ${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        VCS_REF: ${VCS_REF:-$(git rev-parse --short HEAD)}
        VERSION: ${VERSION:-0.1.0}
        EXCHANGE_TYPE: ${EXCHANGE_TYPE:-coinbase}
    container_name: ai-trading-bot-slim
    restart: unless-stopped

    # Memory constraints for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

    environment:
      # Memory optimization
      - ENABLE_MEMORY_OPTIMIZATION=true
      - MAX_MEMORY_MB=450
      - PYTHONOPTIMIZE=2
      - MALLOC_TRIM_THRESHOLD_=100000

      # Trading configuration
      - EXCHANGE__EXCHANGE_TYPE=${EXCHANGE_TYPE:-coinbase}
      - TRADING_MODE=${TRADING_MODE:-paper}
      - DRY_RUN=${DRY_RUN:-true}

      # Coinbase credentials (if using live trading)
      - COINBASE__API_KEY=${COINBASE_API_KEY}
      - COINBASE__API_SECRET=${COINBASE_API_SECRET}

      # OpenAI (optional - remove if not using AI features)
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1

    volumes:
      # Minimal volume mounts
      - ./config:/app/config:ro
      - ./data:/app/data
      - ./logs:/app/logs

    ports:
      - "8080:8080"

    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

    # Security constraints
    read_only: false  # Set to true if possible
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID

    # Network isolation
    networks:
      - trading-network

networks:
  trading-network:
    driver: bridge
    internal: false

# Optional: Add volume for persistent data
volumes:
  trading-data:
    driver: local
