# Bluefin Override - Use with main docker-compose.yml
services:
  # Configure for Bluefin mode
  ai-trading-bot:
    environment:
      - EXCHANGE__EXCHANGE_TYPE=bluefin
      - BLUEFIN_ENABLED=true
      - TRADING__SYMBOL=BTC-PERP
      - EXCHANGE__BLUEFIN_NETWORK=testnet

  # Ensure Bluefin service runs
  bluefin-service:
    profiles: []  # Remove profile restriction
    environment:
      - BLUEFIN_NETWORK=testnet
      - BLUEFIN_PRIVATE_KEY=${EXCHANGE__BLUEFIN_PRIVATE_KEY:-0x0000000000000000000000000000000000000000000000000000000000000000}
