# Docker Compose for AI Trading Bot with Dashboard

services:
  ai-trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-trading-bot:latest
    container_name: ai-trading-bot
    restart: unless-stopped
    
    # Override the default command - use --no-dry-run for live trading
    command: ["sh", "-c", "echo 'y' | python -m bot.main live --no-dry-run --symbol ETH-USD --interval 5m"]
    
    # Environment variables from .env file
    env_file:
      - .env
    
    # Docker-specific environment overrides (minimal set to avoid conflicts with .env)
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONWARNINGS=ignore::UserWarning,ignore::DeprecationWarning,ignore::SyntaxWarning,ignore::FutureWarning
      - CONFIG_FILE=/app/config/production.json
      # System Configuration
      - SYSTEM__DRY_RUN=${SYSTEM__DRY_RUN:-true}  # Default to paper trading (safe mode)
      # LLM Logging Configuration
      - LLM__ENABLE_COMPLETION_LOGGING=${LLM_ENABLE_COMPLETION_LOGGING:-true}
      - LLM__COMPLETION_LOG_LEVEL=${LLM_COMPLETION_LOG_LEVEL:-INFO}
      - LLM__COMPLETION_LOG_FILE=${LLM_COMPLETION_LOG_FILE:-logs/llm_completions.log}
      - LLM__ENABLE_PERFORMANCE_TRACKING=${LLM_ENABLE_PERFORMANCE_TRACKING:-true}
      - LLM__ENABLE_LANGCHAIN_CALLBACKS=${LLM_ENABLE_LANGCHAIN_CALLBACKS:-true}
      - LLM__LOG_MARKET_CONTEXT=${LLM_LOG_MARKET_CONTEXT:-true}
      # MCP Memory Configuration
      - MCP_ENABLED=${MCP_ENABLED:-true}
      - MCP_SERVER_URL=http://mcp-memory:8765
      # Logging Level
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
    # Volume mounts for persistence and configuration (cleaned up overlapping mounts)
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config:ro  # Read-only config mount
      - ./bot:/app/bot:ro  # Mount bot code with fixes
      
    # Health check configuration
    healthcheck:
      test: ["CMD-SHELL", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
    # Resource limits for safety
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
          
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
    
    # Connect to shared network for dashboard communication
    networks:
      - trading-network
    
    # Depends on MCP memory server if enabled
    depends_on:
      - mcp-memory

  # MCP Memory Server for AI Learning
  mcp-memory:
    build:
      context: ./bot/mcp
      dockerfile: Dockerfile
    image: mcp-memory-server:latest
    container_name: mcp-memory-server
    restart: unless-stopped
    
    environment:
      - MCP_SERVER_PORT=8765
      - MEM0_API_KEY=${MEM0_API_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MEMORY_RETENTION_DAYS=${MCP_MEMORY_RETENTION_DAYS:-90}
      
    volumes:
      - ./data/mcp_memory:/app/data
      - ./logs/mcp:/app/logs
      
    ports:
      - "8765:8765"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
    networks:
      - trading-network
      
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
        reservations:
          memory: 256M
          cpus: '0.1'
          
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Dashboard Backend Service
  dashboard-backend:
    build: 
      context: ./dashboard/backend
      dockerfile: Dockerfile
    container_name: dashboard-backend
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dashboard/backend/logs:/app/logs
      - ./dashboard/backend/data:/app/data
      - ./logs:/app/trading-logs:ro  # Access to trading bot logs
      - ./data:/app/trading-data:ro  # Access to trading bot data
      # Access to LLM completion logs for dashboard analytics
      - ./logs:/app/llm-logs:ro
      - ./logs:/app/decision-logs:ro
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - TRADING_BOT_CONTAINER=ai-trading-bot
    restart: unless-stopped
    depends_on:
      - ai-trading-bot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - trading-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
        reservations:
          memory: 256M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Dashboard Frontend Service (Production)
  dashboard-frontend:
    build:
      context: ./dashboard/frontend
      dockerfile: Dockerfile
      target: production
    container_name: dashboard-frontend
    ports:
      - "3000:8080"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://dashboard-backend:8000
      - VITE_WS_URL=ws://dashboard-backend:8000
    restart: unless-stopped
    networks:
      - trading-network
    depends_on:
      - dashboard-backend
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.2'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Dashboard Frontend Service (Production)
  dashboard-frontend-prod:
    build:
      context: ./dashboard/frontend
      dockerfile: Dockerfile
      target: production
    container_name: dashboard-frontend-prod
    ports:
      - "3001:8080"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://dashboard-backend:8000
      - VITE_WS_URL=ws://dashboard-backend:8000
    restart: unless-stopped
    networks:
      - trading-network
    depends_on:
      - dashboard-backend
    profiles:
      - production
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
        reservations:
          memory: 128M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx reverse proxy for production
  dashboard-nginx:
    image: nginx:alpine
    container_name: dashboard-nginx
    ports:
      - "8080:80"
    volumes:
      - ./dashboard/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dashboard/nginx/conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped
    networks:
      - trading-network
    depends_on:
      - dashboard-backend
      - dashboard-frontend-prod
    profiles:
      - production
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.1'
        reservations:
          memory: 32M
          cpus: '0.05'
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  # Development service (optional) - use with: docker-compose --profile dev up
  ai-trading-bot-dev:
    extends: ai-trading-bot
    container_name: ai-trading-bot-dev
    profiles:
      - dev
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DEBUG=true
      - TESTING=true
      - SYSTEM__DRY_RUN=true
    volumes:
      - .:/app:delegated  # Mount entire project for development
    networks:
      - trading-network
    command: ["python", "-m", "bot.main", "live", "--symbol", "BTC-USD"]

volumes:
  # Dashboard data persistence (trading bot uses bind mounts)
  dashboard-logs:
    name: dashboard-logs
  dashboard-data:
    name: dashboard-data
  dashboard-node-modules:
    name: dashboard-node-modules

networks:
  trading-network:
    name: trading-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16