"""
Type system foundation for the trading bot.

This module provides centralized type definitions, exception hierarchy,
and type guards for improved type safety across the codebase.
"""

from .base_types import (
    AccountId,
    IndicatorDict,
    MarketDataDict,
    OrderId,
    Percentage,
    Price,
    Quantity,
    Symbol,
    Timestamp,
    ValidationResult,
)
from .market_data import (
    AggregatedMarketData,
    CandleData,
    ConnectionState,
    MarketDataQuality,
    MarketDataStatus,
    MarketDepth,
    OrderBook,
    OrderBookLevel,
    OrderType,
    PriceLevel,
    Spread,
    TickerData,
    TradeExecution,
    TradeId,
    TradeSide,
    aggregate_candles,
    is_valid_price as is_valid_market_price,
    is_valid_timestamp,
    is_valid_volume,
)
from .exceptions import (
    BalanceValidationError,
    ExchangeAuthError,
    ExchangeConnectionError,
    ExchangeError,
    IndicatorError,
    LLMError,
    OrderExecutionError,
    PositionValidationError,
    StrategyError,
    TradeValidationError,
    TradingBotError,
    ValidationError,
)
from .guards import (
    ensure_decimal,
    ensure_positive_decimal,
    is_valid_percentage,
    is_valid_price,
    is_valid_quantity,
    is_valid_symbol,
)
from .services import (
    AsyncHealthCheck,
    AsyncServiceValidator,
    ConnectionInfo,
    ConnectionState,
    DiscoveredService,
    DiscoveryMethod,
    DockerService,
    HealthCheckable,
    RetryConfig,
    ServiceCallback,
    ServiceConfig,
    ServiceConnectionError,
    ServiceDependencyError,
    ServiceEndpoint,
    ServiceError,
    ServiceHealth,
    ServiceHealthCheckError,
    ServiceManager,
    ServiceNotFoundError,
    ServiceRegistration,
    ServiceRegistry,
    ServiceStartupError,
    ServiceStatus,
    ServiceTimeoutError,
    create_endpoint,
    create_health_status,
    is_docker_service,
    is_healthy_service,
    is_valid_endpoint,
    validate_service_config,
)

__all__ = [
    # Base types
    "Price",
    "Quantity",
    "Percentage",
    "Timestamp",
    "Symbol",
    "OrderId",
    "AccountId",
    "MarketDataDict",
    "IndicatorDict",
    "ValidationResult",
    # Market data types
    "AggregatedMarketData",
    "CandleData",
    "ConnectionState",
    "MarketDataQuality",
    "MarketDataStatus",
    "MarketDepth",
    "OrderBook",
    "OrderBookLevel",
    "OrderType",
    "PriceLevel",
    "Spread",
    "TickerData",
    "TradeExecution",
    "TradeId",
    "TradeSide",
    # Exceptions
    "TradingBotError",
    "ValidationError",
    "TradeValidationError",
    "BalanceValidationError",
    "PositionValidationError",
    "ExchangeError",
    "ExchangeConnectionError",
    "ExchangeAuthError",
    "OrderExecutionError",
    "StrategyError",
    "LLMError",
    "IndicatorError",
    # Guards
    "is_valid_price",
    "is_valid_quantity",
    "is_valid_percentage",
    "is_valid_symbol",
    "ensure_decimal",
    "ensure_positive_decimal",
    # Market data guards and helpers
    "is_valid_market_price",
    "is_valid_timestamp",
    "is_valid_volume",
    "aggregate_candles",
    # Service types
    "ServiceHealth",
    "ServiceEndpoint",
    "ServiceStatus",
    "ConnectionState",
    "ConnectionInfo",
    "ServiceConfig",
    "RetryConfig",
    "ServiceRegistration",
    "ServiceRegistry",
    "DiscoveryMethod",
    "DiscoveredService",
    # Service protocols
    "DockerService",
    "ServiceManager",
    "HealthCheckable",
    # Service errors
    "ServiceError",
    "ServiceConnectionError",
    "ServiceHealthCheckError",
    "ServiceTimeoutError",
    "ServiceNotFoundError",
    "ServiceStartupError",
    "ServiceDependencyError",
    # Service type guards
    "is_valid_endpoint",
    "is_healthy_service",
    "is_docker_service",
    "validate_service_config",
    # Service utilities
    "create_health_status",
    "create_endpoint",
    # Service type aliases
    "AsyncHealthCheck",
    "AsyncServiceValidator",
    "ServiceCallback",
]
