name: Docker Compose Configuration Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  # Default environment variables for CI/CD (using correct variable names)
  EXCHANGE__EXCHANGE_TYPE: coinbase
  SYSTEM__DRY_RUN: true
  SYSTEM__ENVIRONMENT: development
  TRADING__SYMBOL: BTC-USD
  TRADING__INTERVAL: 1h
  LOG_LEVEL: INFO
  LLM__MODEL_NAME: gpt-4
  LLM__TEMPERATURE: 0.1
  LLM__MAX_TOKENS: 4000
  # Mock API keys for testing (non-functional)
  LLM__OPENAI_API_KEY: sk-test-key-for-ci-cd-only
  EXCHANGE__CDP_API_KEY_NAME: test-coinbase-key
  EXCHANGE__CDP_PRIVATE_KEY: test-coinbase-secret
  EXCHANGE__BLUEFIN_PRIVATE_KEY: test-private-key
  EXCHANGE__BLUEFIN_NETWORK: testnet

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create CI environment file
      run: |
        # Create .env file for CI/CD with safe defaults
        cat > .env << EOF
        # CI/CD Environment Configuration
        EXCHANGE__EXCHANGE_TYPE=${EXCHANGE__EXCHANGE_TYPE}
        SYSTEM__DRY_RUN=${SYSTEM__DRY_RUN}
        SYSTEM__ENVIRONMENT=${SYSTEM__ENVIRONMENT}
        TRADING__SYMBOL=${TRADING__SYMBOL}
        TRADING__INTERVAL=${TRADING__INTERVAL}
        LOG_LEVEL=${LOG_LEVEL}
        LLM__MODEL_NAME=${LLM__MODEL_NAME}
        LLM__TEMPERATURE=${LLM__TEMPERATURE}
        LLM__MAX_TOKENS=${LLM__MAX_TOKENS}

        # Mock credentials for testing (non-functional)
        LLM__OPENAI_API_KEY=${LLM__OPENAI_API_KEY}
        EXCHANGE__CDP_API_KEY_NAME=${EXCHANGE__CDP_API_KEY_NAME}
        EXCHANGE__CDP_PRIVATE_KEY=${EXCHANGE__CDP_PRIVATE_KEY}
        EXCHANGE__BLUEFIN_PRIVATE_KEY=${EXCHANGE__BLUEFIN_PRIVATE_KEY}
        EXCHANGE__BLUEFIN_NETWORK=${EXCHANGE__BLUEFIN_NETWORK}

        # Additional CI settings
        ENABLE_BACKTESTING=false
        ENABLE_PAPER_TRADING=true
        ENABLE_LIVE_TRADING=false
        TESTING=true
        DEBUG=false
        CONFIG_FILE=./config/development.json

        # MCP Configuration
        MCP_ENABLED=false
        OMNISEARCH__ENABLED=true

        # Functional Programming Configuration
        FP_RUNTIME_ENABLED=true
        FP_RUNTIME_MODE=hybrid

        # Host configuration for container builds
        HOST_UID=1000
        HOST_GID=1000
        EOF

    - name: Validate docker-compose configuration
      run: |
        echo "Testing docker-compose configuration..."
        docker-compose -f docker-compose.yml config --quiet
        echo "✅ Docker Compose configuration is valid"

    - name: Test docker-compose config output
      run: |
        echo "Generating docker-compose configuration..."
        docker-compose -f docker-compose.yml config > docker-compose-resolved.yml
        echo "✅ Configuration generated successfully"

    - name: Validate all service definitions
      run: |
        echo "Validating individual services..."

        # Test each service configuration (updated for current services)
        services=("ai-trading-bot" "bluefin-service" "mcp-omnisearch")

        for service in "${services[@]}"; do
          echo "Validating $service..."
          docker-compose -f docker-compose.yml config --services | grep -q "$service"
          if [ $? -eq 0 ]; then
            echo "✅ $service service definition is valid"
          else
            echo "❌ $service service definition is missing or invalid"
            exit 1
          fi
        done

    - name: Test environment variable substitution
      run: |
        echo "Testing environment variable substitution..."

        # Check if key environment variables are properly substituted
        config_output=$(docker-compose -f docker-compose.yml config)

        # Verify critical environment variables are set
        if echo "$config_output" | grep -q "SYSTEM__DRY_RUN.*true"; then
          echo "✅ SYSTEM__DRY_RUN environment variable properly set"
        else
          echo "❌ SYSTEM__DRY_RUN environment variable not found or incorrect"
          echo "Found DRY_RUN references:"
          echo "$config_output" | grep -i dry_run || echo "No DRY_RUN references found"
        fi

        if echo "$config_output" | grep -q "LOG_LEVEL.*INFO"; then
          echo "✅ LOG_LEVEL environment variable properly set"
        else
          echo "❌ LOG_LEVEL environment variable not found or incorrect"
          echo "Found LOG_LEVEL references:"
          echo "$config_output" | grep -i log_level || echo "No LOG_LEVEL references found"
        fi

    - name: Test without .env file (CI/CD scenario)
      run: |
        echo "Testing configuration without .env file..."

        # Remove .env file to simulate CI/CD environment
        rm -f .env

        # Should still work with env_file.required=false
        docker-compose -f docker-compose.yml config --quiet
        echo "✅ Docker Compose works without .env file"

    - name: Test build contexts exist
      run: |
        echo "Verifying build contexts exist..."

        # Check if all build contexts exist (updated for current project structure)
        contexts=("." "./services" "./bot/mcp/omnisearch-server")

        for context in "${contexts[@]}"; do
          if [ -d "$context" ]; then
            echo "✅ Build context $context exists"
          else
            echo "❌ Build context $context is missing"
            exit 1
          fi
        done

    - name: Verify Dockerfile existence
      run: |
        echo "Verifying Dockerfiles exist..."

        dockerfiles=(
          "./Dockerfile"
          "./services/Dockerfile.bluefin"
          "./bot/mcp/omnisearch-server/Dockerfile"
        )

        for dockerfile in "${dockerfiles[@]}"; do
          if [ -f "$dockerfile" ]; then
            echo "✅ $dockerfile exists"
          else
            echo "❌ $dockerfile is missing"
            exit 1
          fi
        done

    - name: Test network configuration
      run: |
        echo "Testing network configuration..."
        config_output=$(docker-compose -f docker-compose.yml config)

        if echo "$config_output" | grep -q "trading-network"; then
          echo "✅ Trading network is properly configured"
        else
          echo "❌ Trading network configuration is missing"
          exit 1
        fi

    - name: Validate health checks
      run: |
        echo "Validating health check configurations..."
        config_output=$(docker-compose -f docker-compose.yml config)

        # Check for health check definitions
        if echo "$config_output" | grep -q "healthcheck"; then
          echo "✅ Health checks are configured"
        else
          echo "⚠️ No health checks found (optional but recommended)"
        fi

    - name: Summary
      run: |
        echo ""
        echo "🎉 All Docker Compose configuration tests passed!"
        echo ""
        echo "✅ Configuration is valid"
        echo "✅ Environment variables are properly handled"
        echo "✅ Missing .env file is handled gracefully"
        echo "✅ All build contexts exist"
        echo "✅ All Dockerfiles exist"
        echo "✅ Network configuration is valid"
        echo ""
        echo "The docker-compose.yml is ready for CI/CD deployment!"
